CREATE DATABASE HAPPYPET

USE HAPPYPET

CREATE TABLE CLIENT (
	CLIENT_ID INT PRIMARY KEY,
	FIRST_NAME NVARCHAR(20) NOT NULL,
	LAST_NAME NVARCHAR(20) NOT NULL,
	PHONE NVARCHAR(15),
	[ADDRESS] NVARCHAR(200),
	EMAIL NVARCHAR(40) UNIQUE NOT NULL,
	[PASSWORD] NVARCHAR(100) NOT NULL,
	[STATE] BIT,
	CREATION_DATE DATETIME DEFAULT GETDATE() NOT NULL,
	MODIFY_DATE DATETIME,
	CREATED_BY INT,
	MODIFIED_BY INT
);

--ALTER TABLE CLIENT
--ALTER COLUMN PHONE NVARCHAR(15);

CREATE TABLE PET (
	PET_ID INT IDENTITY(1,1) PRIMARY KEY,
	[NAME] NVARCHAR(20) NOT NULL,
	SPECIES NVARCHAR(20) NOT NULL,
	RACE NVARCHAR(30),
	GENDER NVARCHAR(10),
	DATE_OF_BIRTH DATETIME,
	AGE INT,
	CREATION_DATE DATETIME DEFAULT GETDATE() NOT NULL,
	MODIFY_DATE DATETIME,
	CREATED_BY INT,
	MODIFIED_BY INT,
	OWNER_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID)
);

CREATE TABLE CLIENT_PET(
	CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
	PET_ID INT FOREIGN KEY REFERENCES PET(PET_ID),
	CREATION_DATE DATETIME DEFAULT GETDATE() NOT NULL,
	MODIFY_DATE DATETIME,
	CREATED_BY INT,
	MODIFIED_BY INT,
	PRIMARY KEY (PET_ID,CLIENT_ID)
)

--Datos de prueba